repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: './.venv/bin/ruff format'
        language: script
        types: [python]
        pass_filenames: true
      - id: ruff-import-sort
        name: ruff-import-sort
        entry: './.venv/bin/ruff check --fix --select I'
        language: script
        types: [python]
        pass_filenames: true
      - id: pytest
        name: pytest
        entry: './.venv/bin/pytest tests/'
        language: script
        types: [python]
        pass_filenames: false