# generated by datamodel-codegen:
#   filename:  category_schema.json
#   timestamp: 2024-09-17T00:34:03+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel

VALID_CATEGORY_FIELDS = ["name", "type", "title", "summary", "description", "media"]


class Media(BaseModel):
    class Config:
        extra = "forbid"

    height: Optional[float] = None
    type: str
    url: str
    width: Optional[float] = None


class Category(BaseModel):
    class Config:
        extra = "forbid"

    description: Optional[str] = None
    media: Optional[Media] = None
    name: Optional[str] = None
    summary: Optional[str] = None
    title: Optional[str] = None
    type: Optional[str] = None


class CategoryResponse(BaseModel):
    class Config:
        extra = "forbid"

    categories: Optional[List[Category]] = None

class SingleCategoryResponse(BaseModel):
    class Config:
        extra = "forbid"

    category: Category