name: store-tui # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: Navigate the Snap Store from the terminal # 79 char long summary
description: |
  A TUI for for navigating the Snap Store.

  Designed using the "Textual" Python Library - https://github.com/textualize/textual/

  - [✅] Browse the Snap Store
  - [✅] Search for Snaps
  - [✅] View Snap Details
  - [✅] Open Store URL in Browser
  - [❌] Install/Modify Snaps directly from the TUI
  - [❌] View Installed Snaps
  - [❌] View Snap Channels and Revisions
  - [❌] Sort and Filter Snaps

contact: alexdlukens@gmail.com
license: "MIT"
website: https://github.com/alexdlukens/snap-store-tui
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots


parts:
  store_tui:
    plugin: nil
    build-packages: [python3-pip, python3, python3-dev, libffi-dev, libssl-dev]
    source: .
    override-build: |
      # check architecture for build env
      ARCH=$CRAFT_ARCH_BUILD_ON
      echo "Building on $ARCH"
      # if arch is not amd64 or arm64, install additional dependencies
      if [ "$ARCH" != "amd64" ] && [ "$ARCH" != "arm64" ]; then
        echo "Installing additional dependencies for $ARCH"
        apt-get update
        apt-get install -y libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
        libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
        libharfbuzz-dev libfribidi-dev libxcb1-dev cargo openssl build-essential pkg-config cmake
      fi

      # set poetry to use virtualenv local to the snap
      python3 -m pip install poetry --break-system-packages
      python3 -m poetry config virtualenvs.in-project true
      python3 -m poetry install
      # copy virtualenv and store_tui dir to install dir
      cp -a -r $CRAFT_PART_BUILD/.venv/. $CRAFT_PART_INSTALL/
      cp -r $CRAFT_PART_BUILD/store_tui/ $CRAFT_PART_INSTALL/
      cp $CRAFT_PART_BUILD/pyproject.toml $CRAFT_PART_INSTALL/
      chmod a+x $CRAFT_PART_INSTALL/store_tui/main.py
      craftctl default
apps:
  store-tui:
    command: bin/python3 $SNAP/store_tui/main.py
    plugs: [network, network-bind, desktop, snapd-control]
    environment:
      PYTHONPATH: $PYTHONPATH:$SNAP

platforms:
  amd64:
  arm64:
  armhf: