name: store-tui # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Navigate the Snap Store from the terminal # 79 char long summary
description: |
  A TUI for for navigating the Snap Store.

  Designed using the "Textual" Python Library - https://github.com/textualize/textual/

  - [✅] Browse the Snap Store
  - [✅] Search for Snaps
  - [✅] View Snap Details
  - [✅] Open Store URL in Browser
  - [❌] Install/Modify Snaps directly from the TUI
  - [❌] View Installed Snaps
  - [❌] View Snap Channels and Revisions
  - [❌] Sort and Filter Snaps

contact: alexdlukens@gmail.com
license: MIT
website: https://github.com/alexdlukens/snap-store-tui
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  store_tui:
    plugin: nil
    build-packages: [python3-pip, python3]
    source: .
    override-build: |
      # set poetry to use virtualenv local to the snap
      python3 -m pip install poetry --break-system-packages
      poetry config virtualenvs.in-project true
      poetry install
      # copy virtualenv and store_tui dir to install dir
      cp -r $CRAFT_PART_BUILD/.venv $CRAFT_PART_INSTALL/
      cp -r $CRAFT_PART_BUILD/store_tui/ $CRAFT_PART_INSTALL/
      craftctl default
    override-stage: |
      # copy virtualenv and store_tui dir to prime dir
      cp -r $CRAFT_PART_INSTALL/.venv $CRAFT_PRIME/
      cp -r $CRAFT_PART_INSTALL/store_tui/ $CRAFT_PRIME/
      craftctl default
apps:
  store-tui:
    command: .venv/bin/python3 store_tui/main.py
    plugs: [network, network-bind]

platforms:
  amd64:
  arm64:
  armhf: